### PR TITLE
Update CSS for the footer link

### PR DESCRIPTION
**Pull request by Pandraghon**

### CODE REVIEW

**Comment by Pandraghon** [comment]
🤔

**Comment by Pandraghon** [comment]
@UnseenFaith ?

**Comment by CyberiumShadow** [comment]
What exactly does this do?

**Comment by Pandraghon** [comment]
The link fits better with the footer : 
 - normal : white, underlined
 - hovered : white

**Comment by CyberiumShadow** [comment]
I'll merge

**Pull request merged**
